// <auto-generated />
using System;
using LaytonTempleTours.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaytonTempleTours.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220326024137_initialyeet")]
    partial class initialyeet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("LaytonTempleTours.Models.Appointment", b =>
                {
                    b.Property<long>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeOfGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TimeId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("LaytonTempleTours.Models.Time", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SlotAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeId");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            TimeId = 1,
                            DateTime = new DateTime(2022, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 2,
                            DateTime = new DateTime(2022, 3, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 3,
                            DateTime = new DateTime(2022, 3, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 4,
                            DateTime = new DateTime(2022, 3, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 5,
                            DateTime = new DateTime(2022, 3, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 6,
                            DateTime = new DateTime(2022, 3, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 7,
                            DateTime = new DateTime(2022, 3, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 8,
                            DateTime = new DateTime(2022, 3, 28, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 9,
                            DateTime = new DateTime(2022, 3, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 10,
                            DateTime = new DateTime(2022, 3, 28, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 11,
                            DateTime = new DateTime(2022, 3, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 12,
                            DateTime = new DateTime(2022, 3, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 13,
                            DateTime = new DateTime(2022, 3, 28, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 14,
                            DateTime = new DateTime(2022, 3, 29, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 15,
                            DateTime = new DateTime(2022, 3, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 16,
                            DateTime = new DateTime(2022, 3, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 17,
                            DateTime = new DateTime(2022, 3, 29, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 18,
                            DateTime = new DateTime(2022, 3, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 19,
                            DateTime = new DateTime(2022, 3, 29, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 20,
                            DateTime = new DateTime(2022, 3, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 21,
                            DateTime = new DateTime(2022, 3, 29, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 22,
                            DateTime = new DateTime(2022, 3, 29, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 23,
                            DateTime = new DateTime(2022, 3, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 24,
                            DateTime = new DateTime(2022, 3, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = false
                        },
                        new
                        {
                            TimeId = 25,
                            DateTime = new DateTime(2022, 3, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 26,
                            DateTime = new DateTime(2022, 3, 29, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 27,
                            DateTime = new DateTime(2022, 3, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 28,
                            DateTime = new DateTime(2022, 3, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 29,
                            DateTime = new DateTime(2022, 3, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 30,
                            DateTime = new DateTime(2022, 3, 30, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 31,
                            DateTime = new DateTime(2022, 3, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 32,
                            DateTime = new DateTime(2022, 3, 30, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 33,
                            DateTime = new DateTime(2022, 3, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 34,
                            DateTime = new DateTime(2022, 3, 30, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 35,
                            DateTime = new DateTime(2022, 3, 30, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 36,
                            DateTime = new DateTime(2022, 3, 30, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 37,
                            DateTime = new DateTime(2022, 3, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 38,
                            DateTime = new DateTime(2022, 3, 30, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 39,
                            DateTime = new DateTime(2022, 3, 30, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 40,
                            DateTime = new DateTime(2022, 3, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 41,
                            DateTime = new DateTime(2022, 3, 31, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 42,
                            DateTime = new DateTime(2022, 3, 31, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 43,
                            DateTime = new DateTime(2022, 3, 31, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 44,
                            DateTime = new DateTime(2022, 3, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 45,
                            DateTime = new DateTime(2022, 3, 31, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 46,
                            DateTime = new DateTime(2022, 3, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 47,
                            DateTime = new DateTime(2022, 3, 31, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 48,
                            DateTime = new DateTime(2022, 3, 31, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 49,
                            DateTime = new DateTime(2022, 3, 31, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 50,
                            DateTime = new DateTime(2022, 3, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 51,
                            DateTime = new DateTime(2022, 3, 31, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 52,
                            DateTime = new DateTime(2022, 3, 31, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 53,
                            DateTime = new DateTime(2022, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 54,
                            DateTime = new DateTime(2022, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 55,
                            DateTime = new DateTime(2022, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 56,
                            DateTime = new DateTime(2022, 4, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 57,
                            DateTime = new DateTime(2022, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 58,
                            DateTime = new DateTime(2022, 4, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 59,
                            DateTime = new DateTime(2022, 4, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 60,
                            DateTime = new DateTime(2022, 4, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 61,
                            DateTime = new DateTime(2022, 4, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 62,
                            DateTime = new DateTime(2022, 4, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 63,
                            DateTime = new DateTime(2022, 4, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 64,
                            DateTime = new DateTime(2022, 4, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 65,
                            DateTime = new DateTime(2022, 4, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 66,
                            DateTime = new DateTime(2022, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 67,
                            DateTime = new DateTime(2022, 4, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 68,
                            DateTime = new DateTime(2022, 4, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 69,
                            DateTime = new DateTime(2022, 4, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 70,
                            DateTime = new DateTime(2022, 4, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 71,
                            DateTime = new DateTime(2022, 4, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 72,
                            DateTime = new DateTime(2022, 4, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 73,
                            DateTime = new DateTime(2022, 4, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 74,
                            DateTime = new DateTime(2022, 4, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 75,
                            DateTime = new DateTime(2022, 4, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 76,
                            DateTime = new DateTime(2022, 4, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 77,
                            DateTime = new DateTime(2022, 4, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 78,
                            DateTime = new DateTime(2022, 4, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 79,
                            DateTime = new DateTime(2022, 4, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 80,
                            DateTime = new DateTime(2022, 4, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 81,
                            DateTime = new DateTime(2022, 4, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 82,
                            DateTime = new DateTime(2022, 4, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 83,
                            DateTime = new DateTime(2022, 4, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 84,
                            DateTime = new DateTime(2022, 4, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 85,
                            DateTime = new DateTime(2022, 4, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 86,
                            DateTime = new DateTime(2022, 4, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 87,
                            DateTime = new DateTime(2022, 4, 3, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 88,
                            DateTime = new DateTime(2022, 4, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 89,
                            DateTime = new DateTime(2022, 4, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 90,
                            DateTime = new DateTime(2022, 4, 3, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        },
                        new
                        {
                            TimeId = 91,
                            DateTime = new DateTime(2022, 4, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotAvailable = true
                        });
                });

            modelBuilder.Entity("LaytonTempleTours.Models.Appointment", b =>
                {
                    b.HasOne("LaytonTempleTours.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
